### ISSUE TITLE
TODO: 確認

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#1]
- 白抜き三角のアイコンの追加について
- 画像の差し替えについて

**Comment by pojiro** [comment]
### 白抜き三角のアイコンの追加について

- [x] fontawesome の 5.15.4, circle, triangle を使う
- [x] CDN を使うようにする

※ https://fontawesome.com/v5/icons/triangle?s=regular&f=classic は Pro でないと使用できないため、 triangle は未表示になります。

### 画像の差し替えについて

- [x] 6 枚分差し替えをする
  - [x] workshop は何かを作るような画像
  - [x] products は製品っぽい画像
- [x] 差し替えた画像の 元URL を [src/images/url.md](https://github.com/pojiro/teamgenik_pub_samples/blob/main/src/images/url.md) に記載する

### 画像の縦横比

- [x] object fit を使い、うまく配置できるか試す。
  - ~~hover したら 大きく広げるとかできるか検討？~~, `object-cover` を使い不要と判断しました

### その他

- [x] HTML 下部の date の並びは 白線で区切りがみえてもいいかも
  - モバイル表示の際に薄灰色の下線を表示させることで、各日付が分かれていることを強調するようにしました。

**Comment by pojiro** [comment]
2/22 に報告したので、本 issue はクローズとする
